name: All Platform Build

on:
    release:
        types: [released]
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
 
    - name: Get Dependencies and PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    #- name: PyInstaller Build Windows
      #run: TODO
      #if: runner.os == 'Windows'
      
    - name: PyInstaller Build Linux
      run: $(cat pyinstaller_linux.txt)
      if: runner.os == 'Linux'

    - name: PyInstaller Build macOS
      run: $(cat pyinstaller_macos.txt)
      if: runner.os == 'macOS'
      
